### ISSUE TITLE
Thread panic: left == right

### ISSUE THREAD

**Issue by nannal** [dabreegster/abstreet#18]
```
load map...
upload textures (14)... 0.0066s
14 textures grouped into 3 arrays (with the same dimensions)
Loading map ../data/system/maps/montlake.bin
Reading ../data/system/maps/montlake.bin: 0/5 MB... 0.000Read ../data/system/maps/montlake.bin (5)... 0.0802s
create sim...
create sim took 0.0028s
Map and Sim cost ~11 MB
draw_map...
make DrawRoads (415)... 0.0384s
generate thick roads...
generate thick roads took 0.0039s
prepare DrawLanes (2,181)... 0.0369s
finalize DrawLanes (2,181)... 0.0447s
make DrawIntersections (317)... 0.0302s
generate unzoomed intersections...
generate unzoomed intersections took 0.0009s
make DrawBuildings (3,018)... 0.0097s
upload all buildings...
upload all buildings took 0.0088s
make DrawBusStop (16)... 0.0003s
make DrawAreas (55)... 0.0000s
upload all areas...
upload all areas took 0.0001s
create quadtree...
create quadtree took 0.0914s
static DrawMap consumes 9 MB on the GPU
draw_map... plus 0.0066s
draw_map took 0.2719s
DrawMap cost ~159 MB
load map... plus 0.0281s
load map took 0.3895s

- load map took 0.3895s
  - upload textures (14)... 0.0066s
  - Read ../data/system/maps/montlake.bin (5)... 0.0802s
  - create sim took 0.0028s
  - draw_map took 0.2719s
    - make DrawRoads (415)... 0.0384s
    - generate thick roads took 0.0039s
    - prepare DrawLanes (2,181)... 0.0369s
    - finalize DrawLanes (2,181)... 0.0447s
    - make DrawIntersections (317)... 0.0302s
    - generate unzoomed intersections took 0.0009s
    - make DrawBuildings (3,018)... 0.0097s
    - upload all buildings took 0.0088s
    - make DrawBusStop (16)... 0.0003s
    - make DrawAreas (55)... 0.0000s
    - upload all areas took 0.0001s
    - create quadtree took 0.0914s
    - ... plus 0.0066s
  - ... plus 0.0281s

5 notes:
14 textures grouped into 3 arrays (with the same dimensions)
Loading map ../data/system/maps/montlake.bin
Map and Sim cost ~11 MB
static DrawMap consumes 9 MB on the GPU
DrawMap cost ~159 MB

1 warnings:
Couldn't make geometry for TurnID(LaneID(531), LaneID(192), IntersectionID(52)). look for Pt2D(336.4989, 876.3308) to Pt2D(355.7037, 866.4475) in [Pt2D { inner_x: 336.3221, inner_y: 891.3298 }, Pt2D { inner_x: 336.4989, inner_y: 876.3308 }, Pt2D { inner_x: 345.5252, inner_y: 876.4371 }, Pt2D { inner_x: 355.3143, inner_y: 866.8297 }, Pt2D { inner_x: 366.594, inner_y: 876.7766 }, Pt2D { inner_x: 366.3413, inner_y: 891.7741 }, Pt2D { inner_x: 353.0851, inner_y: 891.5507 }, Pt2D { inner_x: 349.9952, inner_y: 897.5429 }, Pt2D { inner_x: 336.3221, inner_y: 891.3298 }]

- load map took 0.3895s
instantiate scenario...
instantiate scenario took 0.0000s

- instantiate scenario took 0.0000s

- instantiate scenario took 0.0000s
both CONTEXTUAL: spawn agents around this intersection and CONTEXTUAL: cycle through this lane's turns read key Z
reset simulation...
reset simulation took 0.0034s

- reset simulation took 0.0034s

- reset simulation took 0.0034s
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `ScreenDims { width: 17.7598, height: 17.759799999995707 }`,
 right: `ScreenDims { width: 17.7598, height: 17.759799999999345 }`', ezgui/src/widgets/button.rs:36:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   9: ezgui::widgets::button::Button::new
  10: ezgui::widgets::button::Button::rectangle_svg
  11: game::sandbox::speed::SpeedControls::new
  12: game::sandbox::SandboxMode::new
  13: game::sandbox::gameplay::change_scenario
  14: core::ops::function::Fn::call
  15: <game::game::WizardState as game::game::State>::event
  16: <game::game::Game as ezgui::runner::GUI>::event
  17: std::panicking::try::do_call
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  19: ezgui::runner::State<G>::event
  20: ezgui::runner::run
  21: game::main
  22: std::rt::lang_start::{{closure}}
  23: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  24: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  25: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  26: std::panicking::try
             at src/libstd/panicking.rs:275
  27: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  28: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  29: main
  30: __libc_start_main
  31: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
********************************************************************************
UI broke! Primary sim:
********************************************************************************
At 00:00:00.0

```

Game crashes at various points with the same issue, happy to provide further info as needed.

**Comment by dabreegster** [comment]
If you built from source, you can 'git pull' and try this out. If you're using a binary, then I'll ping this thread when I release a new one in a few days. Thanks!

**Comment by nannal** [comment]
I was lazy & using the bin, I'll keep my eyes out for the ping, thank you.

**Comment by dabreegster** [comment]
https://github.com/dabreegster/abstreet/releases/tag/v0.1.19
I think this one should fix it; please reopen if not
