### ISSUE TITLE
Maintain data from the latest few releases in Dropbox

### ISSUE THREAD

**Issue by yurivict** [dabreegster/abstreet#195]
```
runtime: seattle,krakow
input: seattle,krakow
```

```
> download https://www.dropbox.com/s/nwb29tt4koqk6um/seattle.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/cities/seattle.bin
>   file 0 extracted to "data/system/cities/seattle.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/jmnayehllgvn7fm/ballard.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/jmnayehllgvn7fm/ballard.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/jmnayehllgvn7fm/ballard.bin.zip), continuing
> rm tmp_download.zip
> download https://www.dropbox.com/s/crmtwktcm1vpr85/downtown.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/crmtwktcm1vpr85/downtown.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/crmtwktcm1vpr85/downtown.bin.zip), continuing
> rm tmp_download.zip
> download https://www.dropbox.com/s/friayproln1gtig/huge_krakow.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/friayproln1gtig/huge_krakow.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/friayproln1gtig/huge_krakow.bin.zip), continuing
> rm tmp_download.zip
> download https://www.dropbox.com/s/vdwf9acpo4frmrf/lakeslice.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/vdwf9acpo4frmrf/lakeslice.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/vdwf9acpo4frmrf/lakeslice.bin.zip), continuing
> rm tmp_download.zip
> download https://www.dropbox.com/s/0dnysbp2h7wdaf4/montlake.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/0dnysbp2h7wdaf4/montlake.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/0dnysbp2h7wdaf4/montlake.bin.zip), continuing
> rm tmp_download.zip
> download https://www.dropbox.com/s/ml80y89nh3mhwwu/south_seattle.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/ml80y89nh3mhwwu/south_seattle.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/ml80y89nh3mhwwu/south_seattle.bin.zip), continuing
> rm tmp_download.zip
> download https://www.dropbox.com/s/z38hxojx3x8qpvl/udistrict.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/z38hxojx3x8qpvl/udistrict.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/z38hxojx3x8qpvl/udistrict.bin.zip), continuing
> rm tmp_download.zip
> download https://www.dropbox.com/s/qwpq1askjvson23/west_seattle.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/qwpq1askjvson23/west_seattle.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/qwpq1askjvson23/west_seattle.bin.zip), continuing
> rm tmp_download.zip
> download https://www.dropbox.com/s/z20g7t2x2n9o2qx/weekday.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/z20g7t2x2n9o2qx/weekday.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/z20g7t2x2n9o2qx/weekday.bin.zip), continuing
> rm tmp_download.zip
> download https://www.dropbox.com/s/jefg0ikjy9dsrdd/car%20vs%20bike%20contention.bin.zip?dl=1 to tmp_download.zip
> unzip tmp_download.zip data/system/prebaked_results/montlake/car vs bike contention.bin
>   file 0 extracted to "data/system/prebaked_results/montlake/car vs bike contention.bin"
> rm tmp_download.zip
> download https://www.dropbox.com/s/5q3wqc5bkfrxr0h/weekday.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/5q3wqc5bkfrxr0h/weekday.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/5q3wqc5bkfrxr0h/weekday.bin.zip), continuing
> rm tmp_download.zip
> download https://www.dropbox.com/s/lzvudj2u1ww7v8b/weekday.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/lzvudj2u1ww7v8b/weekday.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/lzvudj2u1ww7v8b/weekday.bin.zip), continuing
> rm tmp_download.zip
> download https://www.dropbox.com/s/1x9l60r33083c1g/weekday.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/1x9l60r33083c1g/weekday.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/1x9l60r33083c1g/weekday.bin.zip), continuing
> rm tmp_download.zip
> download https://www.dropbox.com/s/34ap1bsyo97m4gv/weekday.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/34ap1bsyo97m4gv/weekday.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/34ap1bsyo97m4gv/weekday.bin.zip), continuing
> rm tmp_download.zip
> download https://www.dropbox.com/s/8s1o6xyamx6cv9r/weekday.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/8s1o6xyamx6cv9r/weekday.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/8s1o6xyamx6cv9r/weekday.bin.zip), continuing
> rm tmp_download.zip
> download https://www.dropbox.com/s/ogivpq3pd6aixm6/weekday.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/ogivpq3pd6aixm6/weekday.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/ogivpq3pd6aixm6/weekday.bin.zip), continuing
> rm tmp_download.zip
> download https://www.dropbox.com/s/w3ikv2p5cgplgtd/weekday.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/w3ikv2p5cgplgtd/weekday.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/w3ikv2p5cgplgtd/weekday.bin.zip), continuing
> rm tmp_download.zip
> download https://www.dropbox.com/s/uq07s7rv0frs47h/weekday.bin.zip?dl=1 to tmp_download.zip
error getting https://www.dropbox.com/s/uq07s7rv0frs47h/weekday.bin.zip?dl=1: HTTP status client error (404 Not Found) for url (https://www.dropbox.com/s/dl/uq07s7rv0frs47h/weekday.bin.zip), continuing
> rm tmp_download.zip
thread 'main' panicked at 'Failed to download stuff: ["data/input/raw_maps/huge_krakow.bin", "data/input/seattle/parcels.bin", "data/system/maps/ballard.bin", "data/system/maps/downtown.bin", "data/system/maps/huge_krakow.bin", "data/system/maps/lakeslice.bin", "data/system/maps/montlake.bin", "data/system/maps/south_seattle.bin", "data/system/maps/udistrict.bin", "data/system/maps/west_seattle.bin", "data/system/prebaked_results/lakeslice/weekday.bin", "data/system/prebaked_results/montlake/weekday.bin", "data/system/scenarios/ballard/weekday.bin", "data/system/scenarios/downtown/weekday.bin", "data/system/scenarios/lakeslice/weekday.bin", "data/system/scenarios/montlake/weekday.bin", "data/system/scenarios/south_seattle/weekday.bin", "data/system/scenarios/udistrict/weekday.bin", "data/system/scenarios/west_seattle/weekday.bin"]', updater/src/main.rs:69:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: updater::download::{{closure}}
             at updater/src/main.rs:69
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libcore/future/mod.rs:66
  10: updater::main::{{closure}}
             at updater/src/main.rs:30
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libcore/future/mod.rs:66
  12: tokio::runtime::enter::Enter::block_on::{{closure}}
             at ./cargo-crates/tokio-0.2.21/src/runtime/enter.rs:163
  13: tokio::coop::with_budget::{{closure}}
             at ./cargo-crates/tokio-0.2.21/src/coop.rs:127
  14: std::thread::local::LocalKey<T>::try_with
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libstd/thread/local.rs:263
  15: std::thread::local::LocalKey<T>::with
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libstd/thread/local.rs:239
  16: tokio::coop::with_budget
             at ./cargo-crates/tokio-0.2.21/src/coop.rs:120
  17: tokio::coop::budget
             at ./cargo-crates/tokio-0.2.21/src/coop.rs:96
  18: tokio::runtime::enter::Enter::block_on
             at ./cargo-crates/tokio-0.2.21/src/runtime/enter.rs:163
  19: tokio::runtime::thread_pool::ThreadPool::block_on
             at ./cargo-crates/tokio-0.2.21/src/runtime/thread_pool/mod.rs:82
  20: tokio::runtime::Runtime::block_on::{{closure}}
             at ./cargo-crates/tokio-0.2.21/src/runtime/mod.rs:446
  21: tokio::runtime::context::enter
             at ./cargo-crates/tokio-0.2.21/src/runtime/context.rs:72
  22: tokio::runtime::handle::Handle::enter
             at ./cargo-crates/tokio-0.2.21/src/runtime/handle.rs:76
  23: tokio::runtime::Runtime::block_on
             at ./cargo-crates/tokio-0.2.21/src/runtime/mod.rs:441
  24: updater::main
             at updater/src/main.rs:11
  25: std::rt::lang_start::{{closure}}
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libstd/rt.rs:67
  26: std::rt::lang_start_internal
  27: std::rt::lang_start
             at /wrkdirs/usr/ports/lang/rust/work/rustc-1.44.1-src/src/libstd/rt.rs:67
  28: main
  29: _start
             at /usr/src/lib/csu/amd64/crt1.c:76
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
*** Error code 101

Stop.
```

**Comment by dabreegster** [comment]
Just to check, are you synced to HEAD? I last updated map data at Mon Jul 13 16:07:35 2020 -0700. Only the latest map data is maintained (it'd be a massive amount of storage otherwise), and the URLs unfortunately change every time a new version of a file is uploaded (thanks Dropbox).

**Comment by yurivict** [comment]
> are you synced to HEAD?

No, I use 0.2.3, the last tagged release. I think you should keep files that the last release depends on.

**Comment by dabreegster** [comment]
Agreed. I can start keeping files from the last release or two. Will figure out how to structure the Dropbox directory appropriately.

**Comment by dabreegster** [comment]
Actually, I wonder if it'd be easier on your end to grab `data/` from the assets at https://github.com/dabreegster/abstreet/releases? Github archives these forever, and it'd mean you don't have to run the updater at all.

**Comment by yurivict** [comment]
IMO keeping data for the last 2 releases is better because this allows packagers freedom to choose which data is downloaded and packaged.

**Comment by dabreegster** [comment]
The version of the data and code must match, or there's a risk of binary incompatibility. I agree data needs to be available for HEAD and for the last few tagged releases. I'm just wondering if keeping the release's data in Dropbox is easier, or if a script could download one of the .zip assets and grab data from there. The latter preserves data for all releases, not just the last few.

**Comment by dabreegster** [comment]
The script could be something as simple as

```
VERSION_UNDERSCORES="0_2_3"
VERSION_DOTS="0.2.3"
wget https://github.com/dabreegster/abstreet/releases/download/v${VERSION_DOTS}/abstreet_linux_v${VERSION_UNDERSCORES}.zip;
unzip abstreet_linux_v${VERSION_UNDERSCORES}.zip;
mv abstreet_linux_v${VERSION_UNDERSCORES}/data/system/ ...
```

**Comment by dabreegster** [comment]
@yurivict, I think this bug is almost solved. Sorry it took so long! Data files are now stored in S3, at predictable URLs. When I cut a new release, I make a copy to a directory with the release version, and I'll keep at least the last 2-3 releases around. https://dabreegster.github.io/abstreet/dev/data.html has details (it may took a few minutes after this comment for mdbook to deploy this URL).

I haven't thought through the release process for the FreeBSD package in detail, but I think you can checkout the git repo at a tagged release and run the updater. Actually, I guess you'll also need a way to tell the updater to grab from the versioned directory; I'll push that in a moment.

**Comment by yurivict** [comment]
Ok, thanks, I will try it when I'll have a chance.
