### ISSUE TITLE
Importing city on Windows

### ISSUE THREAD

**Issue by jvolker** [dabreegster/abstreet#232]
Thanks for improving the city importer on Windows as discussed in #119. Unfortunately, I'm still getting errors when importing a city.

Using latest master `set RUST_BACKTRACE=1 && cargo run --release --manifest-path importer/Cargo.toml -- --raw --map --city=berlin` throws:

   ```
 Running `target\release\importer.exe --raw --map --city=berlin`
- Working on all berlin maps
import map data...
- Missing data/input/berlin/osm/berlin-latest.osm.pbf, so downloading http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf
- Running "curl" "--fail" "-L" "-o" "tmp_output" "http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 57.2M  100 57.2M    0     0  11.4M      0  0:00:05  0:00:05 --:--:-- 11.3M
- Missing data/input/berlin/planning_areas.bin, so downloading https://tsb-opendata.s3.eu-central-1.amazonaws.com/lor_planungsgraeume/lor_planungsraeume.kml
- Running "curl" "--fail" "-L" "-o" "tmp_output" "https://tsb-opendata.s3.eu-central-1.amazonaws.com/lor_planungsgraeume/lor_planungsraeume.kml"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2982k  100 2982k    0     0  2982k      0  0:00:01 --:--:--  0:00:01 4341k
- Extracting KML data
extracting shapes from KML...
Opening tmp_output
Read tmp_output (2)... 0.1160s
Read tmp_output (2)... 0.1163s
Got 43 shapes from tmp_output and skipped 406 shapes
extracting shapes from KML... plus 0.0062s
extracting shapes from KML took 0.1302s

- extracting shapes from KML took 0.1302s
  - Reading tmp_output (2 MB)... 0.1241s
  - ... plus 0.0062s

- extracting shapes from KML took 0.1302s
Wrote data/input/berlin/planning_areas.bin
- Missing data/input/berlin/EWR201812E_Matrix.csv, so downloading https://www.statistik-berlin-brandenburg.de/opendata/EWR201812E_Matrix.csv
- Running "curl" "--fail" "-L" "-o" "tmp_output" "https://www.statistik-berlin-brandenburg.de/opendata/EWR201812E_Matrix.csv"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 89337  100 89337    0     0  89337      0  0:00:01 --:--:--  0:00:01  159k
Read data/input/berlin/planning_areas.bin (0)... 0.0028s0.0001s
Wrote data/input/berlin/planning_areas.bin
- Clipping data/input/berlin/osm/berlin-latest.osm.pbf to data/input/berlin/polygons/berlin_center.poly
- Running "osmconvert" "data/input/berlin/osm/berlin-latest.osm.pbf" "-B=data/input/berlin/polygons/berlin_center.poly" "--complete-ways" "-o=data/input/berlin/osm/berlin_center.osm"
thread 'main' panicked at 'Failed to run "osmconvert" "data/input/berlin/osm/berlin-latest.osm.pbf" "-B=data/input/berlin/polygons/berlin_center.poly" "--complete-ways" "-o=data/input/berlin/osm/berlin_center.osm": Os { code: 2, kind: NotFound, message: "Das System kann die angegebene Datei nicht finden." }', importer\src\utils.rs:121:13
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libcore\fmt\mod.rs:1076
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\io\mod.rs:1537
   5: std::sys_common::backtrace::_print
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:486
  10: std::panicking::begin_panic_handler
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:388
  11: std::panicking::begin_panic_fmt
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:342
  12: importer::utils::osmconvert
  13: importer::utils::osmconvert
  14: importer::berlin::osm_to_raw
  15: alloc::collections::btree::search::search_tree
  16: map_model::objects::intersection::_IMPL_SERIALIZE_FOR_IntersectionType::<impl serde::ser::Serialize for map_model::objects::intersection::IntersectionType>::serialize
  17: std::rt::lang_start_internal::{{closure}}
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\rt.rs:52
  18: std::panicking::try::do_call
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:297
  19: std::panicking::try
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:274
  20: std::panic::catch_unwind
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panic.rs:394
  21: std::rt::lang_start_internal
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\rt.rs:51
  22: main
  23: invoke_main
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  24: __scrt_common_main_seh
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  25: BaseThreadInitThunk
  26: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
import map data took 7.4444s

- import map data took 7.4444s

- import map data took 7.4444s
error: process didn't exit successfully: `target\release\importer.exe --raw --map --city=berlin` (exit code: 101)
```

Thanks.

If using Windows becomes too much work to support I could also look into switching to Linux or [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) for our purposes.

**Comment by dabreegster** [comment]
Per https://github.com/dabreegster/abstreet/blob/master/docs/dev.md#building-map-data, could you try installing `osmconvert`?

**Comment by jvolker** [comment]
Oh. Yes, I didn't follow that guide yet. Thanks for mentioning it.

The Windows download for `osmconvert` is an `.exe` file. I'm not sure where to put it or what to do with it.

> Windows users can start osmconvert by double-clicking on the executable.
> 
> Users of all platforms can start osmconvert from the command-line. 

Maybe on Windows command-line mode is not available?

**Comment by dabreegster** [comment]
I'm not familiar with the Windows equivalent of the Linux `$PATH`, which is a list of folders to search for commands. I bet if you put `osmconvert.exe` in the same directory where you're running the importer command, it'll find it. But I'm not sure what best practice is.

**Comment by dabreegster** [comment]
#296 made failures for missing tools happen upfront, and also created a way to override the location of osmconvert.exe
