### ISSUE TITLE
Thread panic when starting Traffic Signals / The Real Challenge

### ISSUE THREAD

**Issue by xoob** [dabreegster/abstreet#25]
Getting this crash when launching the 3rd Traffic Signals challenge.

macOS: 10.14.6-x86_64

```
$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.48s
     Running `/Users/alex/src/github.com/dabreegster/abstreet/target/debug/game`
HiDPI factor is purportedly 2
load map...
upload textures (14)... 0.3988s
14 textures grouped into 3 arrays (with the same dimensions)
Loading map ../data/system/maps/montlake.bin
Read ../data/system/maps/montlake.bin (4)... 0.4818s
create sim...
create sim took 0.0294s
Map and Sim cost ~0 MB
draw_map...
make DrawRoads (415)... 0.2145s
generate thick roads...
generate thick roads took 0.0217s
prepare DrawLanes (2,181)... 0.2386s
finalize DrawLanes (2,181)... 0.1540s
make DrawIntersections (317)... 0.1769s
generate unzoomed intersections...
generate unzoomed intersections took 0.0116s
make DrawBuildings (3,018)... 0.0630s
upload all buildings...
upload all buildings took 0.0168s
make DrawBusStop (16)... 0.0018s
make DrawAreas (55)... 0.0002s
upload all areas...
upload all areas took 0.0004s
create quadtree...
create quadtree took 0.4307s
static DrawMap consumes 9 MB on the GPU
draw_map... plus 0.0455s
draw_map took 1.3758s
DrawMap cost ~0 MB
load map... plus 0.0564s
load map took 2.3422s

- load map took 2.3422s
  - upload textures (14)... 0.3988s
  - Read ../data/system/maps/montlake.bin (4)... 0.4818s
  - create sim took 0.0294s
  - draw_map took 1.3758s
    - make DrawRoads (415)... 0.2145s
    - generate thick roads took 0.0217s
    - prepare DrawLanes (2,181)... 0.2386s
    - finalize DrawLanes (2,181)... 0.1540s
    - make DrawIntersections (317)... 0.1769s
    - generate unzoomed intersections took 0.0116s
    - make DrawBuildings (3,018)... 0.0630s
    - upload all buildings took 0.0168s
    - make DrawBusStop (16)... 0.0018s
    - make DrawAreas (55)... 0.0002s
    - upload all areas took 0.0004s
    - create quadtree took 0.4307s
    - ... plus 0.0455s
  - ... plus 0.0564s

5 notes:
14 textures grouped into 3 arrays (with the same dimensions)
Loading map ../data/system/maps/montlake.bin
Map and Sim cost ~0 MB
static DrawMap consumes 9 MB on the GPU
DrawMap cost ~0 MB

1 warnings:
Couldn't make geometry for TurnID(LaneID(531), LaneID(192), IntersectionID(52)). look for Pt2D(336.4989, 876.3308) to Pt2D(355.7037, 866.4475) in [Pt2D { inner_x: 336.3221, inner_y: 891.3298 }, Pt2D { inner_x: 336.4989, inner_y: 876.3308 }, Pt2D { inner_x: 345.5252, inner_y: 876.4371 }, Pt2D { inner_x: 355.3143, inner_y: 866.8297 }, Pt2D { inner_x: 366.594, inner_y: 876.7766 }, Pt2D { inner_x: 366.3413, inner_y: 891.7741 }, Pt2D { inner_x: 353.0851, inner_y: 891.5507 }, Pt2D { inner_x: 349.9952, inner_y: 897.5429 }, Pt2D { inner_x: 336.3221, inner_y: 891.3298 }]

- load map took 2.3422s
instantiate scenario...
Read ../data/system/scenarios/montlake/weekday_typical_traffic_from_psrc.bin (1)... 0.1352s
Instantiating weekday_typical_traffic_from_psrc...
load full neighborhood info...
load_all_objects from ../data/input/neighborhoods/montlake...
load_all_objects from ../data/input/neighborhoods/montlake took 0.0000s

- load_all_objects from ../data/input/neighborhoods/montlake took 0.0000s

- load_all_objects from ../data/input/neighborhoods/montlake took 0.0000s
load full neighborhood info took 0.0676s
seed individual parked cars (1,875)... 0.1517s
SpawnTrip (26,975)... 0.0230s
thread '<unnamed>' panicked at 'SidewalkEndpoint(LaneID(1186), false) not in NodeMap', map_model/src/pathfind/node_map.rs:36:13
stack backtrace:
thread '<unnamed>' panicked at 'SidewalkEndpoint(LaneID(467), false) not in NodeMap', map_model/src/pathfind/node_map.rs:36:13
thread '<unnamed>' panicked at 'SidewalkEndpoint(LaneID(2100), true) not in NodeMap', map_model/src/pathfind/node_map.rs:36:13
thread '<unnamed>' panicked at 'SidewalkEndpoint(LaneID(1186), false) not in NodeMap', map_model/src/pathfind/node_map.rs:36:13
thread '<unnamed>' panicked at 'SidewalkEndpoint(LaneID(708), false) not in NodeMap', map_model/src/pathfind/node_map.rs:36:13
thread '<unnamed>' panicked at 'SidewalkEndpoint(LaneID(1186), false) not in NodeMap', map_model/src/pathfind/node_map.rs:36:13
thread '<unnamed>' panicked at 'SidewalkEndpoint(LaneID(1186), false) not in NodeMap', map_model/src/pathfind/node_map.rs:36:13
thread '<unnamed>' panicked at 'SidewalkEndpoint(LaneID(398), true) not in NodeMap', map_model/src/pathfind/node_map.rs:36:13
   0: std::io::Read::read_exact
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::continue_panic_fmt
   7: crossbeam_epoch::internal::Global::try_advance
   8: map_model::pathfind::node_map::NodeMap<T>::get
             at map_model/src/pathfind/node_map.rs:36
   9: map_model::pathfind::walking::SidewalkPathfinder::pathfind
             at map_model/src/pathfind/walking.rs:98
  10: map_model::pathfind::Pathfinder::pathfind
             at map_model/src/pathfind/mod.rs:437
  11: map_model::map::Map::pathfind
             at map_model/src/map.rs:595
  12: sim::make::spawner::TripSpawner::spawn_all::{{closure}}
             at sim/src/make/spawner.rs:196
  13: abstutil::time::Timer::parallelize::{{closure}}::{{closure}}
             at /Users/alex/src/github.com/dabreegster/abstreet/abstutil/src/time.rs:335
  14: <F as scoped_threadpool::FnBox>::call_box
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:71
  15: scoped_threadpool::Pool::new::{{closure}}
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:127
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::io::Read::read_exact
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::continue_panic_fmt
   7: crossbeam_epoch::internal::Global::try_advance
   8: map_model::pathfind::node_map::NodeMap<T>::get
             at map_model/src/pathfind/node_map.rs:36
   9: map_model::pathfind::walking::SidewalkPathfinder::pathfind
             at map_model/src/pathfind/walking.rs:98
  10: map_model::pathfind::Pathfinder::pathfind
             at map_model/src/pathfind/mod.rs:437
  11: map_model::map::Map::pathfind
             at map_model/src/map.rs:595
  12: sim::make::spawner::TripSpawner::spawn_all::{{closure}}
             at sim/src/make/spawner.rs:196
  13: abstutil::time::Timer::parallelize::{{closure}}::{{closure}}
             at /Users/alex/src/github.com/dabreegster/abstreet/abstutil/src/time.rs:335
  14: <F as scoped_threadpool::FnBox>::call_box
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:71
  15: scoped_threadpool::Pool::new::{{closure}}
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:127
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::io::Read::read_exact
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::continue_panic_fmt
   7: crossbeam_epoch::internal::Global::try_advance
   8: map_model::pathfind::node_map::NodeMap<T>::get
             at map_model/src/pathfind/node_map.rs:36
   9: map_model::pathfind::walking::SidewalkPathfinder::pathfind
             at map_model/src/pathfind/walking.rs:98
  10: map_model::pathfind::Pathfinder::pathfind
             at map_model/src/pathfind/mod.rs:437
  11: map_model::map::Map::pathfind
             at map_model/src/map.rs:595
  12: sim::make::spawner::TripSpawner::spawn_all::{{closure}}
             at sim/src/make/spawner.rs:196
  13: abstutil::time::Timer::parallelize::{{closure}}::{{closure}}
             at /Users/alex/src/github.com/dabreegster/abstreet/abstutil/src/time.rs:335
  14: <F as scoped_threadpool::FnBox>::call_box
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:71
  15: scoped_threadpool::Pool::new::{{closure}}
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:127
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::io::Read::read_exact
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::continue_panic_fmt
   7: crossbeam_epoch::internal::Global::try_advance
   8: map_model::pathfind::node_map::NodeMap<T>::get
             at map_model/src/pathfind/node_map.rs:36
   9: map_model::pathfind::walking::SidewalkPathfinder::pathfind
             at map_model/src/pathfind/walking.rs:98
  10: map_model::pathfind::Pathfinder::pathfind
             at map_model/src/pathfind/mod.rs:437
  11: map_model::map::Map::pathfind
             at map_model/src/map.rs:595
  12: sim::make::spawner::TripSpawner::spawn_all::{{closure}}
             at sim/src/make/spawner.rs:196
  13: abstutil::time::Timer::parallelize::{{closure}}::{{closure}}
             at /Users/alex/src/github.com/dabreegster/abstreet/abstutil/src/time.rs:335
  14: <F as scoped_threadpool::FnBox>::call_box
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:71
  15: scoped_threadpool::Pool::new::{{closure}}
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:127
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::io::Read::read_exact
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::continue_panic_fmt
   7: crossbeam_epoch::internal::Global::try_advance
   8: map_model::pathfind::node_map::NodeMap<T>::get
             at map_model/src/pathfind/node_map.rs:36
   9: map_model::pathfind::walking::SidewalkPathfinder::pathfind
             at map_model/src/pathfind/walking.rs:98
  10: map_model::pathfind::Pathfinder::pathfind
             at map_model/src/pathfind/mod.rs:437
  11: map_model::map::Map::pathfind
             at map_model/src/map.rs:595
  12: sim::make::spawner::TripSpawner::spawn_all::{{closure}}
             at sim/src/make/spawner.rs:196
  13: abstutil::time::Timer::parallelize::{{closure}}::{{closure}}
             at /Users/alex/src/github.com/dabreegster/abstreet/abstutil/src/time.rs:335
  14: <F as scoped_threadpool::FnBox>::call_box
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:71
  15: scoped_threadpool::Pool::new::{{closure}}
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:127
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::io::Read::read_exact
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::continue_panic_fmt
   7: crossbeam_epoch::internal::Global::try_advance
   8: map_model::pathfind::node_map::NodeMap<T>::get
             at map_model/src/pathfind/node_map.rs:36
   9: map_model::pathfind::walking::SidewalkPathfinder::pathfind
             at map_model/src/pathfind/walking.rs:98
  10: map_model::pathfind::Pathfinder::pathfind
             at map_model/src/pathfind/mod.rs:437
  11: map_model::map::Map::pathfind
             at map_model/src/map.rs:595
  12: sim::make::spawner::TripSpawner::spawn_all::{{closure}}
             at sim/src/make/spawner.rs:196
  13: abstutil::time::Timer::parallelize::{{closure}}::{{closure}}
             at /Users/alex/src/github.com/dabreegster/abstreet/abstutil/src/time.rs:335
  14: <F as scoped_threadpool::FnBox>::call_box
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:71
  15: scoped_threadpool::Pool::new::{{closure}}
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:127
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::io::Read::read_exact
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::continue_panic_fmt
   7: crossbeam_epoch::internal::Global::try_advance
   8: map_model::pathfind::node_map::NodeMap<T>::get
             at map_model/src/pathfind/node_map.rs:36
   9: map_model::pathfind::walking::SidewalkPathfinder::pathfind
             at map_model/src/pathfind/walking.rs:98
  10: map_model::pathfind::Pathfinder::pathfind
             at map_model/src/pathfind/mod.rs:437
  11: map_model::map::Map::pathfind
             at map_model/src/map.rs:595
  12: sim::make::spawner::TripSpawner::spawn_all::{{closure}}
             at sim/src/make/spawner.rs:196
  13: abstutil::time::Timer::parallelize::{{closure}}::{{closure}}
             at /Users/alex/src/github.com/dabreegster/abstreet/abstutil/src/time.rs:335
  14: <F as scoped_threadpool::FnBox>::call_box
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:71
  15: scoped_threadpool::Pool::new::{{closure}}
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:127
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::io::Read::read_exact
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::continue_panic_fmt
   7: crossbeam_epoch::internal::Global::try_advance
   8: map_model::pathfind::node_map::NodeMap<T>::get
             at map_model/src/pathfind/node_map.rs:36
   9: map_model::pathfind::walking::SidewalkPathfinder::pathfind
             at map_model/src/pathfind/walking.rs:99
  10: map_model::pathfind::Pathfinder::pathfind
             at map_model/src/pathfind/mod.rs:437
  11: map_model::map::Map::pathfind
             at map_model/src/map.rs:595
  12: sim::make::spawner::TripSpawner::spawn_all::{{closure}}
             at sim/src/make/spawner.rs:196
  13: abstutil::time::Timer::parallelize::{{closure}}::{{closure}}
             at /Users/alex/src/github.com/dabreegster/abstreet/abstutil/src/time.rs:335
  14: <F as scoped_threadpool::FnBox>::call_box
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:71
  15: scoped_threadpool::Pool::new::{{closure}}
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:127
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0: std::io::Read::read_exact
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::continue_panic_fmt
   7: std::panicking::try::do_call
   8: std::thread::local::fast::Key<T>::try_initialize
   9: std::thread::local::fast::Key<T>::try_initialize
  10: core::option::Option<T>::unwrap
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libcore/macros.rs:12
  11: abstutil::time::Timer::parallelize::{{closure}}::{{closure}}
             at /Users/alex/src/github.com/dabreegster/abstreet/abstutil/src/time.rs:345
  12: core::iter::adapters::map_fold::{{closure}}
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libcore/iter/adapters/mod.rs:694
  13: core::iter::traits::iterator::Iterator::fold::ok::{{closure}}
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libcore/iter/traits/iterator.rs:1813
  14: core::iter::traits::iterator::Iterator::try_fold
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libcore/iter/traits/iterator.rs:1694
  15: core::iter::traits::iterator::Iterator::fold
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libcore/iter/traits/iterator.rs:1816
  16: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libcore/iter/adapters/mod.rs:727
  17: core::iter::traits::iterator::Iterator::for_each
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libcore/iter/traits/iterator.rs:616
  18: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/liballoc/vec.rs:1966
  19: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/liballoc/vec.rs:1949
  20: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/liballoc/vec.rs:1836
  21: core::iter::traits::iterator::Iterator::collect
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libcore/iter/traits/iterator.rs:1478
  22: abstutil::time::Timer::parallelize::{{closure}}
             at /Users/alex/src/github.com/dabreegster/abstreet/abstutil/src/time.rs:345
  23: scoped_threadpool::Pool::scoped
             at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:181
  24: abstutil::time::Timer::parallelize
             at /Users/alex/src/github.com/dabreegster/abstreet/abstutil/src/time.rs:325
  25: sim::make::spawner::TripSpawner::spawn_all
             at sim/src/make/spawner.rs:191
  26: sim::sim::Sim::spawn_all_trips
             at sim/src/sim.rs:162
  27: <map_model::turn::TurnPriority as core::cmp::PartialEq>::eq
  28: game::sandbox::gameplay::GameplayRunner::initialize::{{closure}}
             at game/src/sandbox/gameplay/mod.rs:161
  29: ezgui::event_ctx::EventCtx::loading_screen
             at /Users/alex/src/github.com/dabreegster/abstreet/ezgui/src/event_ctx.rs:41
  30: game::sandbox::gameplay::GameplayRunner::initialize
             at game/src/sandbox/gameplay/mod.rs:157
  31: game::sandbox::SandboxMode::new
             at game/src/sandbox/mod.rs:76
  32: <game::challenges::ChallengeSplash as game::game::State>::event
             at game/src/challenges.rs:238
  33: <game::game::Game as ezgui::runner::GUI>::event
             at game/src/game.rs:44
  34: ezgui::runner::State<G>::event::{{closure}}
             at /Users/alex/src/github.com/dabreegster/abstreet/ezgui/src/runner.rs:84
  35: core::ops::function::FnOnce::call_once
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libcore/ops/function.rs:227
  36: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/panic.rs:315
  37: std::panicking::try::do_call
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/panicking.rs:292
  38: panic_unwind::imp::find_eh_action::{{closure}}
  39: std::panicking::try
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/panicking.rs:271
  40: std::panic::catch_unwind
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/panic.rs:394
  41: ezgui::runner::State<G>::event
             at /Users/alex/src/github.com/dabreegster/abstreet/ezgui/src/runner.rs:83
  42: ezgui::runner::loop_forever
             at /Users/alex/src/github.com/dabreegster/abstreet/ezgui/src/runner.rs:359
  43: ezgui::runner::run
             at /Users/alex/src/github.com/dabreegster/abstreet/ezgui/src/runner.rs:302
  44: game::main
             at game/src/main.rs:51
  45: std::rt::lang_start::{{closure}}
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/rt.rs:64
  46: std::panicking::try::do_call
  47: panic_unwind::imp::find_eh_action::{{closure}}
  48: std::io::lazy::Lazy<T>::get
  49: std::rt::lang_start
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/rt.rs:64
  50: game::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1165:5
stack backtrace:
   0:        0x1081135e5 - std::io::Read::read_exact::ha476307323a9a57b
   1:        0x108139b21 - core::fmt::ArgumentV1::show_usize::h40e0340afa3a9ee9
   2:        0x1081241b9 - std::io::Write::write_fmt::ha9661be3deb7aad2
   3:        0x108115bea - std::panicking::default_hook::{{closure}}::h3c4469e572d8fcea
   4:        0x10811593f - std::panicking::default_hook::h244274cbfa0d3cb9
   5:        0x1081162a7 - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::h33d686882e2a2672
   6:        0x108115e1d - std::panicking::continue_panic_fmt::h851031a5cf31ba4c
   7:        0x108115d79 - std::panicking::try::do_call::h3aa3549642d783df
   8:        0x108153b7f - std::thread::local::fast::Key<T>::try_initialize::h55fced50a298c0af
   9:        0x108153fb9 - std::thread::local::fast::Key<T>::try_initialize::h55fced50a298c0af
  10:        0x107e8d2ad - core::result::Result<T,E>::unwrap::hdca1da400a11ce20
                               at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libcore/result.rs:933
  11:        0x107e782a9 - scoped_threadpool::Scope::join_all::he6f74dc78450ed0b
                               at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:219
  12:        0x107e78415 - <scoped_threadpool::Scope as core::ops::drop::Drop>::drop::h4b5d9b5b13efe1ef
                               at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:248
  13:        0x1070e20c5 - core::ptr::real_drop_in_place::h57eb0164e6bb365f
                               at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libcore/ptr/mod.rs:175
  14:        0x106e80ce0 - scoped_threadpool::Pool::scoped::hb68545791b186de6
                               at /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:182
  15:        0x106a981ef - abstutil::time::Timer::parallelize::hd5cc3ce748441df6
                               at /Users/alex/src/github.com/dabreegster/abstreet/abstutil/src/time.rs:325
  16:        0x1070be5f4 - sim::make::spawner::TripSpawner::spawn_all::h6f46e1c8611b6f39
                               at sim/src/make/spawner.rs:191
  17:        0x1070246a5 - sim::sim::Sim::spawn_all_trips::h73bfa56349a4f28f
                               at sim/src/sim.rs:162
  18:        0x1069ab8e0 - <map_model::turn::TurnPriority as core::cmp::PartialEq>::eq::ha02220298fee37d6
  19:        0x106711d45 - game::sandbox::gameplay::GameplayRunner::initialize::{{closure}}::h1a1bd31a101f754d
                               at game/src/sandbox/gameplay/mod.rs:161
  20:        0x106665126 - ezgui::event_ctx::EventCtx::loading_screen::h8caa7fd526d3198e
                               at /Users/alex/src/github.com/dabreegster/abstreet/ezgui/src/event_ctx.rs:41
  21:        0x1066d2407 - game::sandbox::gameplay::GameplayRunner::initialize::h7bafab8fed6c38b0
                               at game/src/sandbox/gameplay/mod.rs:157
  22:        0x1065bad2b - game::sandbox::SandboxMode::new::h7687e77ed3d06bbf
                               at game/src/sandbox/mod.rs:76
  23:        0x10639c90f - <game::challenges::ChallengeSplash as game::game::State>::event::h0c4b7841e4c9f336
                               at game/src/challenges.rs:238
  24:        0x1067ff5ee - <game::game::Game as ezgui::runner::GUI>::event::hf53ccfb7d00d6a8c
                               at game/src/game.rs:44
  25:        0x1067620c5 - ezgui::runner::State<G>::event::{{closure}}::h4e47f32b19ff1ce0
                               at /Users/alex/src/github.com/dabreegster/abstreet/ezgui/src/runner.rs:84
  26:        0x106554614 - core::ops::function::FnOnce::call_once::hc3a2e5be5dc66136
                               at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libcore/ops/function.rs:227
  27:        0x10678f038 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf7b93e74b0bd4b50
                               at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/panic.rs:315
  28:        0x106510e96 - std::panicking::try::do_call::h0b9aea9dcf53dc0b
                               at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/panicking.rs:292
  29:        0x108125c9f - panic_unwind::imp::find_eh_action::{{closure}}::h6188ae3b2a38145e
  30:        0x106510c95 - std::panicking::try::hc0bf3bc28c2cdc38
                               at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/panicking.rs:271
  31:        0x10678f088 - std::panic::catch_unwind::h9b53761c20aa24f1
                               at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/panic.rs:394
  32:        0x106761a2b - ezgui::runner::State<G>::event::h9fdbf33d5b3ab8e3
                               at /Users/alex/src/github.com/dabreegster/abstreet/ezgui/src/runner.rs:83
  33:        0x1067605a9 - ezgui::runner::loop_forever::h6ebaf94046c7706f
                               at /Users/alex/src/github.com/dabreegster/abstreet/ezgui/src/runner.rs:359
  34:        0x106762abc - ezgui::runner::run::h66b4b43869c6c909
                               at /Users/alex/src/github.com/dabreegster/abstreet/ezgui/src/runner.rs:302
  35:        0x10654fe21 - game::main::h793c540866a10097
                               at game/src/main.rs:51
  36:        0x10674f632 - std::rt::lang_start::{{closure}}::hb62e2bce6ebefdd7
                               at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/rt.rs:64
  37:        0x108115d08 - std::panicking::try::do_call::h3aa3549642d783df
  38:        0x108125c9f - panic_unwind::imp::find_eh_action::{{closure}}::h6188ae3b2a38145e
  39:        0x10811c043 - std::io::lazy::Lazy<T>::get::hef7f4e305e19331d
  40:        0x10674f612 - std::rt::lang_start::h03d6d2c10aef788b
                               at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/rt.rs:64
  41:        0x10654ff52 - game::main::h793c540866a10097
thread panicked while panicking. aborting.
[1]    5654 illegal hardware instruction  RUST_BACKTRACE=1 cargo run
```

**Comment by dabreegster** [comment]
I think this is the same as https://github.com/dabreegster/abstreet/issues/19#issuecomment-565213847. Run grab_seed_data and try again, if you don't mind

**Comment by xoob** [comment]
Also works after grabbing new seed data. 👍
