### ISSUE TITLE
Thread panic when starting sandbox

### ISSUE THREAD

**Issue by xoob** [dabreegster/abstreet#26]
Getting a crash when starting random scenario in sandbox mode.

 - Launch game
 - Click Play
 - Click Sandbox
 - Type <kbd>s</kbd>
 - Choose "random scenario with some agents"
 - Kaboom! 💥

macOS: 10.14.6-x86_64
abstreet: ed2f703e

```
$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.64s
     Running `/Users/alex/src/github.com/dabreegster/abstreet/target/debug/game`
HiDPI factor is purportedly 2
load map...
upload textures (14)... 0.4140s
14 textures grouped into 3 arrays (with the same dimensions)
Loading map ../data/system/maps/montlake.bin
Read ../data/system/maps/montlake.bin (4)... 0.4663s
create sim...
create sim took 0.0271s
Map and Sim cost ~0 MB
draw_map...
make DrawRoads (415)... 0.1948s
generate thick roads...
generate thick roads took 0.0238s
prepare DrawLanes (2,181)... 0.2146s
finalize DrawLanes (2,181)... 0.1464s
make DrawIntersections (317)... 0.1605s
generate unzoomed intersections...
generate unzoomed intersections took 0.0098s
make DrawBuildings (3,018)... 0.0558s
upload all buildings...
upload all buildings took 0.0130s
make DrawBusStop (16)... 0.0012s
make DrawAreas (55)... 0.0002s
upload all areas...
upload all areas took 0.0003s
create quadtree...
create quadtree took 0.4566s
static DrawMap consumes 9 MB on the GPU
draw_map... plus 0.0500s
draw_map took 1.3268s
DrawMap cost ~0 MB
load map... plus 0.0522s
load map took 2.2864s

- load map took 2.2864s
  - upload textures (14)... 0.4140s
  - Read ../data/system/maps/montlake.bin (4)... 0.4663s
  - create sim took 0.0271s
  - draw_map took 1.3268s
    - make DrawRoads (415)... 0.1948s
    - generate thick roads took 0.0238s
    - prepare DrawLanes (2,181)... 0.2146s
    - finalize DrawLanes (2,181)... 0.1464s
    - make DrawIntersections (317)... 0.1605s
    - generate unzoomed intersections took 0.0098s
    - make DrawBuildings (3,018)... 0.0558s
    - upload all buildings took 0.0130s
    - make DrawBusStop (16)... 0.0012s
    - make DrawAreas (55)... 0.0002s
    - upload all areas took 0.0003s
    - create quadtree took 0.4566s
    - ... plus 0.0500s
  - ... plus 0.0522s

5 notes:
14 textures grouped into 3 arrays (with the same dimensions)
Loading map ../data/system/maps/montlake.bin
Map and Sim cost ~0 MB
static DrawMap consumes 9 MB on the GPU
DrawMap cost ~0 MB

1 warnings:
Couldn't make geometry for TurnID(LaneID(531), LaneID(192), IntersectionID(52)). look for Pt2D(336.4989, 876.3308) to Pt2D(355.7037, 866.4475) in [Pt2D { inner_x: 336.3221, inner_y: 891.3298 }, Pt2D { inner_x: 336.4989, inner_y: 876.3308 }, Pt2D { inner_x: 345.5252, inner_y: 876.4371 }, Pt2D { inner_x: 355.3143, inner_y: 866.8297 }, Pt2D { inner_x: 366.594, inner_y: 876.7766 }, Pt2D { inner_x: 366.3413, inner_y: 891.7741 }, Pt2D { inner_x: 353.0851, inner_y: 891.5507 }, Pt2D { inner_x: 349.9952, inner_y: 897.5429 }, Pt2D { inner_x: 336.3221, inner_y: 891.3298 }]

- load map took 2.2864s
instantiate scenario...
instantiate scenario took 0.0000s

- instantiate scenario took 0.0000s

- instantiate scenario took 0.0000s
reset simulation...
reset simulation took 0.0301s

- reset simulation took 0.0301s

- reset simulation took 0.0301s
instantiate scenario...
Instantiating small_run...
load full neighborhood info...
load_all_objects from ../data/input/neighborhoods/montlake...
load_all_objects from ../data/input/neighborhoods/montlake took 0.0001s

- load_all_objects from ../data/input/neighborhoods/montlake took 0.0001s

- load_all_objects from ../data/input/neighborhoods/montlake took 0.0001s
load full neighborhood info took 0.0693s
seed parked cars for buildings (3,018)... 0.0530s
Seeded 1471 of 5102 parking spots with cars, leaving 1547 buildings without cars
thread 'main' panicked at 'SidewalkEndpoint(LaneID(989), true) not in NodeMap', map_model/src/pathfind/node_map.rs:36:13
stack backtrace:
   0: std::io::Read::read_exact
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::continue_panic_fmt
   7: crossbeam_epoch::internal::Global::try_advance
   8: map_model::pathfind::node_map::NodeMap<T>::get
             at map_model/src/pathfind/node_map.rs:36
   9: map_model::pathfind::walking::SidewalkPathfinder::should_use_transit
             at map_model/src/pathfind/walking.rs:171
  10: map_model::pathfind::Pathfinder::should_use_transit
             at map_model/src/pathfind/mod.rs:450
  11: map_model::map::Map::should_use_transit
             at map_model/src/map.rs:603
  12: sim::make::scenario::SpawnOverTime::spawn_agent
  13: <map_model::turn::TurnPriority as core::cmp::PartialEq>::eq
  14: game::sandbox::gameplay::GameplayRunner::initialize::{{closure}}
             at game/src/sandbox/gameplay/mod.rs:161
  15: ezgui::event_ctx::EventCtx::loading_screen
             at /Users/alex/src/github.com/dabreegster/abstreet/ezgui/src/event_ctx.rs:41
  16: game::sandbox::gameplay::GameplayRunner::initialize
             at game/src/sandbox/gameplay/mod.rs:157
  17: game::sandbox::SandboxMode::new
             at game/src/sandbox/mod.rs:76
  18: game::sandbox::gameplay::change_scenario
             at game/src/sandbox/gameplay/mod.rs:224
  19: core::ops::function::Fn::call
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libcore/ops/function.rs:69
  20: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/liballoc/boxed.rs:936
  21: <game::game::WizardState as game::game::State>::event
             at game/src/game.rs:218
  22: <game::game::Game as ezgui::runner::GUI>::event
             at game/src/game.rs:44
  23: ezgui::runner::State<G>::event::{{closure}}
             at /Users/alex/src/github.com/dabreegster/abstreet/ezgui/src/runner.rs:84
  24: core::ops::function::FnOnce::call_once
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libcore/ops/function.rs:227
  25: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/panic.rs:315
  26: std::panicking::try::do_call
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/panicking.rs:292
  27: panic_unwind::imp::find_eh_action::{{closure}}
  28: std::panicking::try
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/panicking.rs:271
  29: std::panic::catch_unwind
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/panic.rs:394
  30: ezgui::runner::State<G>::event
             at /Users/alex/src/github.com/dabreegster/abstreet/ezgui/src/runner.rs:83
  31: ezgui::runner::loop_forever
             at /Users/alex/src/github.com/dabreegster/abstreet/ezgui/src/runner.rs:359
  32: ezgui::runner::run
             at /Users/alex/src/github.com/dabreegster/abstreet/ezgui/src/runner.rs:302
  33: game::main
             at game/src/main.rs:51
  34: std::rt::lang_start::{{closure}}
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/rt.rs:64
  35: std::panicking::try::do_call
  36: panic_unwind::imp::find_eh_action::{{closure}}
  37: std::io::lazy::Lazy<T>::get
  38: std::rt::lang_start
             at /private/tmp/rust-20191107-43598-2ji78o/rustc-1.39.0-src/src/libstd/rt.rs:64
  39: game::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
dropping Timer while doing progress SpawnOverTime each agent, due to panic?
********************************************************************************
UI broke! Primary sim:
********************************************************************************
At 00:00:00.0
Wrote ../data/player/camera_state/montlake.json
```

**Comment by dabreegster** [comment]
I think this is the same as https://github.com/dabreegster/abstreet/issues/19#issuecomment-565213847. Run grab_seed_data and try again, if you don't mind

**Comment by xoob** [comment]
Works after grabbing new seed data. 👍
