### ISSUE TITLE
Crash during 'Jump to next delay' on Downtown Seattle

### ISSUE THREAD

**Issue by FLHerne** [dabreegster/abstreet#260]
Using commit `a797af2d5` "new release", compiled locally on Arch Linux with rustc 1.45.0.

 * Enter Sandbox mode
 * Load the map "Downtown Seattle".
 * Select "Jump to the next delay over 5 minutes"

The timewarp window appears for a second or two, then the sim crashes with the output and stacktrace below.

This is reproducible every time, for me at least.

```
switch map...
Wrote data/player/camera_state/montlake.json
load map...
Loading map data/system/maps/downtown.bin
Read data/system/maps/downtown.bin (26)... 1.5094s
create sim...
create sim took 0.1598s
Map and Sim cost ~68 MB
draw_map...
make DrawRoads (3,064)... 0.9182s
make DrawLanes (16,278)... 0.1538s
make DrawIntersections (2,116)... 1.5903s
generate unzoomed roads and intersections...
generate unzoomed roads and intersections took 0.0503s
make DrawBuildings (8,081)... 0.5371s
upload all buildings...
upload all buildings took 0.1200s
make DrawParkingLot...
make DrawParkingLot took 0.3492s
make DrawBusStop (276)... 0.0989s
make DrawAreas (271)... 0.0006s
upload all areas...
upload all areas took 0.0012s
create quadtree...
create quadtree took 1.0160s
static DrawMap consumes 95 MB on the GPU
draw_map... plus 0.2771s
draw_map took 5.1125s
DrawMap cost ~166 MB
load map... plus 0.0020s
load map took 6.7837s

- load map took 6.7837s
  - Read data/system/maps/downtown.bin (26)... 1.5094s
  - create sim took 0.1598s
  - draw_map took 5.1125s
    - make DrawRoads (3,064)... 0.9182s
    - make DrawLanes (16,278)... 0.1538s
    - make DrawIntersections (2,116)... 1.5903s
    - generate unzoomed roads and intersections took 0.0503s
    - make DrawBuildings (8,081)... 0.5371s
    - upload all buildings took 0.1200s
    - make DrawParkingLot took 0.3492s
    - make DrawBusStop (276)... 0.0989s
    - make DrawAreas (271)... 0.0006s
    - upload all areas took 0.0012s
    - create quadtree took 1.0160s
    - ... plus 0.2771s
  - ... plus 0.0020s

4 notes:
Loading map data/system/maps/downtown.bin
Map and Sim cost ~68 MB
static DrawMap consumes 95 MB on the GPU
DrawMap cost ~166 MB

- load map took 6.7837s
reset simulation...
reset simulation took 0.1495s

- reset simulation took 0.1495s

- reset simulation took 0.1495s
setup challenge...
Read data/system/scenarios/downtown/weekday.bin (70)... 5.3673s
Instantiating weekday...
trips for People: 62,308/359,319... 0.6000sBike trip from Building #6860 to Building #6834 will just walk; it's the same sidewalk!
trips for People: 82,326/359,319... 0.8001sBike trip from Building #5832 to Building #7002 will just walk; it's the same sidewalk!
Bike trip from Building #2530 to Building #2647 will just walk; it's the same sidewalk!
trips for People: 98,753/359,319... 1.0001sBike trip from Building #2359 to Building #2374 will just walk; it's the same sidewalk!
Bike trip from Building #2374 to Building #2359 will just walk; it's the same sidewalk!
trips for People: 141,666/359,319... 1.4001sBike trip from Building #7570 to Building #2153 will just walk; it's the same sidewalk!
Bike trip from Building #6580 to Building #6977 will just walk; it's the same sidewalk!
trips for People: 159,465/359,319... 1.6001sBike trip from Building #1765 to Building #1780 will just walk; it's the same sidewalk!
trips for People: 181,256/359,319... 1.8001sBike trip from Building #7488 to Building #6670 will just walk; it's the same sidewalk!
trips for People (359,319)... 3.3504s
seed parked cars (72,559)... 1.4205s
calculate paths (1,132,332)... 4.9134s
spawn trips (1,132,332)... 10.9031s
Instantiating weekday... plus 6.6886s
Instantiating weekday took 27.2760s
WARNING: Bus #88 wants to spawn past their end on a one-step path
WARNING: Bus #82 wants to spawn past their end on a one-step path
*<many repeats with different numbers>*

No prebaked simulation results for "weekday" scenario on downtown map. This means trip dashboards can't compare current times to any kind of baseline.
setup challenge... plus 0.1698s
setup challenge took 32.8131s

- setup challenge took 32.8131s
  - Read data/system/scenarios/downtown/weekday.bin (70)... 5.3673s
  - Instantiating weekday took 27.2760s
    - trips for People (359,319)... 3.3504s
    - seed parked cars (72,559)... 1.4205s
    - calculate paths (1,132,332)... 4.9134s
    - spawn trips (1,132,332)... 10.9031s
    - ... plus 6.6886s
  - ... plus 0.1698s

- setup challenge took 32.8131s
switch map took 39.9410s

- switch map took 39.9410s

- switch map took 39.9410s
WARNING: Bus #88 wants to spawn past their end on a one-step path
WARNING: Bus #82 wants to spawn past their end on a one-step path
*<many, many repeats with different numbers>*

On Traversable::Lane(11653) at 00:01:00.0...
- Bus #68 @ 108.095m (length 12.5m)
  Queued currently
- Bus #67 @ 74.358m (length 12.5m)
  Idling during 00:00:51.6 .. 00:01:01.6
- Bus #66 @ 60.858m (length 12.5m)
  Queued currently
- Bus #65 @ 47.358m (length 12.5m)
  Queued currently
- Bus #64 @ 33.858m (length 12.5m)
  Queued currently
- Bus #63 @ 20.358m (length 12.5m)
  Queued currently
- Bus #62 @ 6.858m (length 12.5m)
  Queued currently

thread 'main' panicked at 'Queue has spillover on Traversable::Lane(11653) at 00:01:00.0 -- can't draw Bus #60, bound is -6.642m. Laggy head is Some(CarID(69, Bus)). This is usually a geometry bug; check for duplicate roads going between the same intersections.', sim/src/mechanics/queue.rs:125:17
stack backtrace:
   0:     0x562d3b36de05 - backtrace::backtrace::libunwind::trace::h77fbb5c507b33a0e
                               at /build/rust/src/rustc-1.45.0-src/vendor/backtrace/src/backtrace/libunwind.rs:86
   1:     0x562d3b36de05 - backtrace::backtrace::trace_unsynchronized::h91cbaf53235bafe5
                               at /build/rust/src/rustc-1.45.0-src/vendor/backtrace/src/backtrace/mod.rs:66
   2:     0x562d3b36de05 - std::sys_common::backtrace::_print_fmt::h24f4beb5944d42f8
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x562d3b36de05 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h331f87bdfe431e03
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x562d3b3967ec - core::fmt::write::h6119538332b9e6d2
                               at src/libcore/fmt/mod.rs:1076
   5:     0x562d3b3677a3 - std::io::Write::write_fmt::h88dea6e9ce58ad66
                               at src/libstd/io/mod.rs:1537
   6:     0x562d3b3705b0 - std::sys_common::backtrace::_print::h7a9346c61b70a8ff
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x562d3b3705b0 - std::sys_common::backtrace::print::h71098ca5aa84aadb
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x562d3b3705b0 - std::panicking::default_hook::{{closure}}::h5ce7a160abffade2
                               at src/libstd/panicking.rs:198
   9:     0x562d3b3702fc - std::panicking::default_hook::hf1ac76ef7ece3f39
                               at src/libstd/panicking.rs:218
  10:     0x562d3b370be7 - std::panicking::rust_panic_with_hook::hd9cd2dfdf3868c9c
                               at src/libstd/panicking.rs:486
  11:     0x562d3b3707eb - rust_begin_unwind
                               at src/libstd/panicking.rs:388
  12:     0x562d3b37075b - std::panicking::begin_panic_fmt::hd6ce6606199a7308
                               at src/libstd/panicking.rs:342
  13:     0x562d3ad127c8 - sim::mechanics::queue::Queue::inner_get_car_positions::hcb7893830e476974
  14:     0x562d3ad3366d - sim::mechanics::driving::DrivingSimState::get_unzoomed_agents::hd5569afcc1e163b1
  15:     0x562d3ad20c43 - <sim::sim::Sim as sim::render::GetDrawAgents>::get_unzoomed_agents::hf62012ea5449e842
  16:     0x562d3aab8da6 - game::render::map::AgentCache::draw_unzoomed_agents::hdf510b1a5ce73d1a
  17:     0x562d3a884206 - game::app::App::draw::hf9f441861478da60
  18:     0x562d3aa2c51d - <game::sandbox::speed::TimeWarpScreen as game::game::State>::draw::h6900e0a0d7587173
  19:     0x562d3a987ef7 - <game::game::Game as ezgui::runner::GUI>::draw::he343eb87e370eb38
  20:     0x562d3aaa6bec - ezgui::runner::State<G>::draw::hcc695e0783856768
  21:     0x562d3a90623a - ezgui::runner::run::{{closure}}::hf849cc00cb2209d6
  22:     0x562d3aa47ec8 - winit::platform_impl::platform::x11::EventLoop<T>::run::hadd997414b80edbd
  23:     0x562d3a90c456 - winit::platform_impl::platform::EventLoop<T>::run::h00596175e663e373
  24:     0x562d3aaa9ff2 - winit::event_loop::EventLoop<T>::run::hf32be41e7be38194
  25:     0x562d3aaa7873 - ezgui::runner::run::h1096bd428b86e7c5
  26:     0x562d3aa64058 - game::main::ha7a717a15d6b8633
  27:     0x562d3a8e8d73 - std::rt::lang_start::{{closure}}::hb6198976f9797dc2
  28:     0x562d3b371078 - std::rt::lang_start_internal::{{closure}}::hccafdc8ea5b5866e
                               at src/libstd/rt.rs:52
  29:     0x562d3b371078 - std::panicking::try::do_call::h19ed3eccb2821851
                               at src/libstd/panicking.rs:297
  30:     0x562d3b371078 - std::panicking::try::hb894e812a150ef31
                               at src/libstd/panicking.rs:274
  31:     0x562d3b371078 - std::panic::catch_unwind::hfac326f7a8874b2e
                               at src/libstd/panic.rs:394
  32:     0x562d3b371078 - std::rt::lang_start_internal::hcbe90c8ee5b8835c
                               at src/libstd/rt.rs:51
  33:     0x562d3aa64552 - main
  34:     0x7fe271a48002 - __libc_start_main
  35:     0x562d3a7f62ee - _start
  36:                0x0 - <unknown>

********************************************************************************
Wrote data/player/camera_state/downtown.json
Crash! Please report to https://github.com/dabreegster/abstreet/issues/ and include all output.txt; at least everything starting from the stack trace above!

At 00:01:00.0

Camera:
{ "cam_x": 1437.893538790049, "cam_y": 964.9444925334536, "cam_zoom": 0.5178488921463198 }

No edits

Crash! Please report to https://github.com/dabreegster/abstreet/issues/ and include all output.txt; at least everything above here until the start of the report!
********************************************************************************
```

**Comment by dabreegster** [comment]
If you `git pull` and re-run the updater, this should be fixed. If you hit a crash like "Car #123635 at 01:18:00.0 has front at 0.01m of Lane(LaneID(15046)). Didn't even wind up with two points", I'm working on that now. :)   Just added some more stringent testing to catch this sort of regression before a release.
